#!/usr/bin/env bash
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo_safe.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
python cartpole_ppo.py &
