# Configuaration for the goal hazard car environement

experiment_name : 'car_goal_hazard_sac'

environment:
  #The environment to use
  robot_base: 'xmls/car.xml'
  task : 'goal'
  observation_flatten : True
  observe_goal_lidar : True
  observe_hazards : True
  constrain_hazards : True
  # lidar_max_dist : 3
  lidar_num_bins : 16
  hazards_num : 4
  observe_sensors : False # Disable visualizations of internal sensors for simpler state management    
  continue_goal: False  # If true, draw a new goal after achievement
  lidar_max_dist: 100  # Maximum distance for lidar sensitivity (if None, exponential distance)

render : False
epochs : 100
steps_per_epoch : 10000 #10000

#agent parameters
min_epsilon: 0.01
parameters:
  alpha : 0.1

#ON POLICY parameters
on_policy : False

# OFF POLICY parameters
off_policy : True
update_frequency: 512 #execute a step of training after this number of environment steps
steps_in_future:  10
batch_size: 64

discount_factor: 0.99

has_continuous_action_space : True
